export type ProductCondition = "new" | "used";
export type ProductStatus = "active" | "sold" | "paused";

export interface Location {
  city: string;
  country: string;
}

export interface Product {
  id: string; // ID assigned by Firestore
  title: string;
  description: string;
  price: number;
  currency: string; // e.g. "COP"
  sellerId: string;
  sellerName: string;
  sellerPhoto: string | null;
  images: string[]; // Un array de Firebase Storage URLs
  video?: string; // Opcional Firebase Storage URL
  category: string;
  tags: string[];
  location: Location;
  condition: ProductCondition;
  status: ProductStatus;
  views: number;
  likes: number;
  createdAt: number; // Guardado como number (Date.now()) o Timestamp.toMillis() para asegurar SSR compatibility en Next.js
  updatedAt: number;
}

/**
 * Interface type when creating a new product from the frontend.
 * We omit autogenerated fields and seller data that we can grab from context.
 */
export interface CreateProductInput extends Omit<Product, "id" | "sellerId" | "sellerName" | "sellerPhoto" | "views" | "likes" | "createdAt" | "updatedAt" | "status" | "images"> {
  images: File[]; // El frontend mandará Objetos File temporales para subida
  video?: string; // Opcional si permitimos subir videos, para este scope, lo ignoramos de momento en local uploads o aceptamos File
}

export type UpdateProductInput = Partial<Omit<Product, "id" | "sellerId" | "createdAt" | "views" | "likes">>;
